### ISSUE TITLE
Can't get a new repo added after previous repos were checked out

### ISSUE THREAD

**Issue by SJLC** [sarnold/repolite#4]
When I add a new repo to the config file, I can't figure out how to get it checked out along with the existing ones.

**To Reproduce**
1. Create a config file with some repos
2. `repolite` to clone those repos
3. Add another repo to config file
4. `repolite` 
    ERROR:root:Top dir: Git cannot clone with existing directories

I thought that `repolite` would clone the new repo that is missing from the local dir

**Comment by sarnold** [comment]
You are correct, that is not (yet) a feature. I will look at that next...

**Comment by SJLC** [comment]
Thanks
